# This file is autogenerated with dep2bazel, do not edit.
load("@io_bazel_rules_go//go:def.bzl", "go_repository")

def go_deps():

    go_repository(
        name = "com_github_golang_protobuf",
        importpath = "github.com/golang/protobuf",
        urls = ["https://github.com/golang/protobuf/archive/925541529c1fa6821df4e44ce2723319eb2be768.tar.gz"],
        strip_prefix = "protobuf-925541529c1fa6821df4e44ce2723319eb2be768/",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
    )

    go_repository(
        name = "org_golang_x_net",
        importpath = "golang.org/x/net",
        urls = ["https://github.com/golang/net/archive/b3c676e531a6dc479fa1b35ac961c13f5e2b4d2e.tar.gz"],
        strip_prefix = "net-b3c676e531a6dc479fa1b35ac961c13f5e2b4d2e/",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
    )

    go_repository(
        name = "org_golang_x_text",
        importpath = "golang.org/x/text",
        urls = ["https://github.com/golang/text/archive/f21a4dfb5e38f5895301dc265a8def02365cc3d0.tar.gz"],
        strip_prefix = "text-f21a4dfb5e38f5895301dc265a8def02365cc3d0/",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
    )

    go_repository(
        name = "org_golang_google_genproto",
        importpath = "google.golang.org/genproto",
        urls = ["https://github.com/google/go-genproto/archive/35de2414665fc36f56b72d982c5af480d86de5ab.tar.gz"],
        strip_prefix = "go-genproto-35de2414665fc36f56b72d982c5af480d86de5ab/",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
    )

    go_repository(
        name = "org_golang_google_grpc",
        importpath = "google.golang.org/grpc",
        urls = ["https://github.com/grpc/grpc-go/archive/d89cded64628466c4ab532d1f0ba5c220459ebe8.tar.gz"],
        strip_prefix = "grpc-go-d89cded64628466c4ab532d1f0ba5c220459ebe8/",
        build_file_generation = "on",
        build_file_proto_mode = "disable",
    )
